# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('jmspots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sender', models.DateTimeField(blank=True, null=True)),
                ('date_receivers', models.DateTimeField(blank=True, null=True)),
                ('with_card', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jmspots.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Receivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('DECLINED', 'DECLINED'), ('NULL', 'NULL')], default='NULL', max_length=20)),
                ('list_receivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_receivers', to='users.User')),
                ('receivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmrequests.Request')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_receivers', to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='receivers',
            field=models.ManyToManyField(through='jmrequests.Request_Receivers', to='users.User'),
        ),
        migrations.AddField(
            model_name='request',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmspots.Spot'),
        ),
    ]
