"""
Django settings for wiri project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import pymysql
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5wqo9k+w7w(*27*psok&2+*5=!7g!)6%i=)84&=&bx%c&a1ki7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



### DEBUG = False Décommenter

# ALLOWED_HOSTS = ['192.168.1.48','127.0.0.1']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'jmspots.apps.JmspotsConfig',
    'jmrequests.apps.JmrequestsConfig',
    'chatroom.apps.ChatroomConfig',
    'rest_framework',
    'fcm'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.common.BrokenLinkEmailsMiddleware',
]

ROOT_URLCONF = 'wiri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


ADMINS = (
    ('Alioune Mane', 'aliounemane2@gmail.com'),
	('Thiame Sow', 'thiamesow@gmail.com'),
	('Thiame Sow 2', 'thiame.sow@qualshore.com'),

)

SEND_BROKEN_LINK_EMAILS= True
MANAGERS = ADMINS



WSGI_APPLICATION = 'wiri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {

    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wiri_db3',
        #'NAME': 'wiri_db1',
        'USER': 'root',
        'PASSWORD': '',
        #'PASSWORD': 'Qsroot15',

        'HOST': '127.0.0.1',
        'PORT': '',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

# La Bonne    USE_L10N = True
# Dernirenement USE_L10N = False
USE_L10N = True

# La bonne     USE_TZ = True
# dernierement USE_TZ = False
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_FILE_PATH = '/static/'
#EMAIL_PORT = 25
EMAIL_PORT = 587
EMAIL_HOST_USER = 'aliounemane2@gmail.com'
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True
FILE_CHARSET = 'utf-8'
DEFAULT_FROM_EMAIL = 'WIRI - GROUP <aliounemane2@gmail.com>'




LOGIN_REDIRECT_URL='accueil'


TWILIO_ACCOUNT_SID = 'AC149fc8ff0f95e8bd6ec2a56d81b751ff'
TWILIO_AUTH_TOKEN = 'f2e2c35a7aa9ccfa46cc07606fbd635a'


# NEXMO_API_KEY = '6d792c50'
# NEXMO_API_SECRET = 'b6082b3c77e561cf'
# NEXMO_DEFAULT_FROM = 'WIRI'
#
# NEXMO_USERNAME = 'aliounemane2@gmail.com'
# NEXMO_PASSWORD = '771096893P@pa'


# FCM_APIKEY = "AIzaSyAKnjfNJ-ju8XLAJTxOhKnWyV2oyxJwkaQ"
#FCM_APIKEY = "AAAAlRkKZUk:APA91bEhOYqI3k3begKtAPVlAmworWXzGl0v7s37pQbxtoErEj-JP7wM5DklNOwgPFKuWnX9g-pfda9zp_V6ouhgywGL3kNLf_wBvhanXOI4vYr80UN7nvWOezRMWr_xvcS3kyMWYbQ5"



FCM_APIKEY = "AIzaSyCz4hrWr2MkUPq8C41JC5ZGzM9w7T97ESs"


######## FCM_SENDER_ID = "839722819865"
# FCM_SENDER_ID = "wiri-53379"
# FCM_SENDER_ID = "839722819865"

FCM_MAX_RECIPIENTS = 1000

FCM_SETTINGS = {
    ###### "FCM_SENDER_ID" : "839722819865",
    "FCM_SERVER_KEY": "AIzaSyCz4hrWr2MkUPq8C41JC5ZGzM9w7T97ESs"
}



# FCM_DEVICE_MODEL = 'fcm.Device'
FCM_DEVICE_MODEL = 'users.MyDevice'


#FCM_DEVICE_MODEL = 'users.models.MyDevice'


#FCM_DEVICE_MODEL = 'users.models.Device'
#FCM_DEVICE_MODEL = 'users.models.MyDevice'

# FCM_DEVICE_MODEL = 'users.Device'
# AUTH_USER_MODEL = 'users.models'



DATETIME_INPUT_FORMATS = [
    '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M',        # '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M:%S.%f',  # '2006-10-25 14:30:59.000200'
    '%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
    '%Y-%m-%d',              # '2006-10-25'
    '%m/%d/%Y %H:%M:%S',     # '10/25/2006 14:30:59'
    '%m/%d/%Y %H:%M:%S.%f',  # '10/25/2006 14:30:59.000200'
    '%m/%d/%Y %H:%M',        # '10/25/2006 14:30'
    '%m/%d/%Y',              # '10/25/2006'
    '%m/%d/%y %H:%M:%S',     # '10/25/06 14:30:59'
    '%m/%d/%y %H:%M:%S.%f',  # '10/25/06 14:30:59.000200'
    '%m/%d/%y %H:%M',        # '10/25/06 14:30'
    '%m/%d/%y',              # '10/25/06'
    # NEMA
    '%Y-%m-%dT%H:%M:%S',  # '2006-10-25 14:30:59'
    '%Y-%m-%dT%H:%M',  # '2006-10-25 14:30'
    '%m/%d/%yT%H:%M:%S',  # '10/25/06 14:30:59'
    '%m/%d/%yT%H:%M:%S.%f',  # '10/25/06 14:30:59.000200'
    '%m/%d/%yT%H:%M',  # '10/25/06 14:30'
    '%m/%d/%y',

    # NEMA 1
    '%d/%m/%yT%H:%M:%S',  # '10/25/06 14:30:59'
    '%d/%m/%yT%H:%M:%S.%f',  # '10/25/06 14:30:59.000200'
    '%d/%m/%yT%H:%M',  # '10/25/06 14:30'
    '%d/%m/%y',
    '%d/%m/%y %H:%M:%S'

]



TIME_INPUT_FORMATS = [

    '%H:%M:%S',  # '14:30:59'
    '%H:%M:%S.%f',  # '14:30:59.000200'
    '%H:%M',  # '14:30'
]


