# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatroom', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='cards/')),
                ('jm_tag', models.CharField(max_length=150, unique=True)),
                ('type_card', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=105)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('chatroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatroom.ChatGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('DECLINED', 'DECLINED'), ('NULL', 'NULL')], default='NULL', max_length=20)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmspots.Card')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_card', to='users.User')),
                ('users_receivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_receivers_card', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserCardFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('card', models.ManyToManyField(to='jmspots.Card')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_cardfavourite', to='users.User')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmspots.Spot'),
        ),
        migrations.AddField(
            model_name='event',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmspots.Spot'),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmspots.Category'),
        ),
        migrations.AddField(
            model_name='card',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jmspots.Event'),
        ),
        migrations.AddField(
            model_name='card',
            name='institution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jmspots.Institution'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
