# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
