# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0003_usercard_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_begin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            # field=models.DateField(blank=True, null=True),
            field=models.DateField(),
        ),
    ]
