# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0008_auto_20170512_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
