# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0009_auto_20170512_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardfavourite',
            name='state',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED')], default='RECEIVED', max_length=20),
        ),
    ]
