# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0011_horaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaires',
            name='days',
            field=models.CharField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche'), (8, '')], max_length=1),
        ),
    ]
