# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0013_auto_20170531_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaires',
            name='time_degin2',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='horaires',
            name='time_end2',
            field=models.TimeField(),
        ),
    ]
