# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0014_auto_20170531_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='horaires',
            field=models.ManyToManyField(to='jmspots.Horaires'),
        ),
    ]
