# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0015_institution_horaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='horaires',
        ),
    ]
