# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0016_remove_institution_horaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaires',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jmspots.Institution'),
        ),
    ]
