# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmspots', '0017_horaires_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaires',
            name='time_degin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horaires',
            name='time_degin2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horaires',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horaires',
            name='time_end2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
