# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20170526_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 15, 47, 38, 177268)),
        ),
    ]
