# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_auto_20170531_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
